/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task by ID */
        get: operations["getTaskById"];
        /** Update a task and optionally its reference repository */
        put: operations["updateTask"];
        post?: never;
        /** Delete a task and its reference repository */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/labs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get laboratory work by ID */
        get: operations["getLabById"];
        /** Update a laboratory work */
        put: operations["updateLab"];
        post?: never;
        /** Delete a laboratory work */
        delete: operations["deleteLab"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/{id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload task solution (ZIP) */
        post: operations["uploadSolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/{id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check own solution */
        post: operations["checkSolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparison/compare-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare two Git repositories provided as ZIP files */
        post: operations["compareFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user (Basic Auth verification) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tasks */
        get: operations["getAllTasks"];
        put?: never;
        /** Create a new task with reference repository */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all students with their submissions */
        get: operations["getAllStudents"];
        put?: never;
        /** Create a new student */
        post: operations["createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{studentId}/assign/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign task to student */
        post: operations["assignTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/submissions/{submissionId}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade student submission */
        post: operations["gradeSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/submissions/{submissionId}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check submission solution (Admin) */
        post: operations["checkSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all laboratory works */
        get: operations["getAllLabs"];
        put?: never;
        /** Create a new laboratory work */
        post: operations["createLab"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/student/api/student/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all laboratory works with assigned tasks for current student */
        get: operations["getLabs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user info */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{studentId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all submissions for a specific student */
        get: operations["getStudentSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all student submissions */
        get: operations["getAllSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/labs/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tasks for a specific laboratory work */
        get: operations["getTasksByLabId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/students/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove task assignment/submission and its file */
        delete: operations["removeAssignment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LaboratoryWork: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number?: number;
            topic?: string;
            description?: string;
            /** Format: double */
            maxGrade?: number;
            tasks?: components["schemas"]["Task"][];
        };
        Task: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number?: number;
            description?: string;
            referenceRepoPath?: string;
            lab?: components["schemas"]["LaboratoryWork"];
        };
        StudentSubmission: {
            /** Format: int64 */
            id?: number;
            task?: components["schemas"]["Task"];
            student?: components["schemas"]["User"];
            studentRepoPath?: string;
            /** Format: double */
            grade?: number;
            feedback?: string;
            /** Format: date-time */
            submittedAt?: string;
        };
        User: {
            /** Format: int64 */
            id?: number;
            username?: string;
            password?: string;
            firstName?: string;
            lastName?: string;
            middleName?: string;
            /** @enum {string} */
            role?: "ADMIN" | "STUDENT";
        };
        AuthorDto: {
            name?: string;
            email?: string;
        };
        CompareResultDto: {
            matchedHashes1To2?: {
                [key: string]: string;
            };
        };
        DiffDto: {
            value?: string;
            state?: string;
        };
        GitComparisonResultDto: {
            type: string;
        } & (components["schemas"]["TwoGraphComparisonResultDto"] | components["schemas"]["MergedGraphComparisonResultDto"]);
        GitGraphDto: {
            nodes?: components["schemas"]["NodeDto"][];
            links?: components["schemas"]["LinkDto"][];
        };
        LinkDto: {
            source?: string;
            target?: string;
        };
        MergedGraphComparisonResultDto: Omit<components["schemas"]["GitComparisonResultDto"], "type"> & {
            mergedGraph?: components["schemas"]["GitGraphDto"];
            compareResult?: components["schemas"]["CompareResultDto"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MergedGraphComparisonResultDto";
        };
        NodeDto: {
            id?: string;
            /** Format: int32 */
            number?: number;
            hash?: string;
            message?: string;
            commitDate?: string;
            authorDate?: string;
            author?: components["schemas"]["AuthorDto"];
            diffs?: components["schemas"]["DiffDto"][];
            severity?: string;
        };
        TwoGraphComparisonResultDto: Omit<components["schemas"]["GitComparisonResultDto"], "type"> & {
            firstGraph?: components["schemas"]["GitGraphDto"];
            secondGraph?: components["schemas"]["GitGraphDto"];
            compareResult?: components["schemas"]["CompareResultDto"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TwoGraphComparisonResultDto";
        };
        SubmissionDto: {
            /** Format: int64 */
            labId?: number;
            /** Format: int32 */
            labNumber?: number;
            /** Format: int64 */
            taskId?: number;
            taskName?: string;
            /** Format: int64 */
            submissionId?: number;
            /** Format: double */
            grade?: number;
            exists?: boolean;
        };
        UserResponseDto: {
            /** Format: int64 */
            id?: number;
            username?: string;
            role?: string;
            firstName?: string;
            lastName?: string;
            middleName?: string;
            submissions?: components["schemas"]["SubmissionDto"][];
        };
        UserCreateDto: {
            username?: string;
            password?: string;
            firstName?: string;
            lastName?: string;
            middleName?: string;
        };
        LaboratoryWorkDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number?: number;
            topic?: string;
            description?: string;
            /** Format: double */
            maxGrade?: number;
            tasks?: components["schemas"]["TaskDto"][];
        };
        TaskDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            number?: number;
            description?: string;
            /** Format: double */
            grade?: number;
            feedback?: string;
            /** Format: date-time */
            submittedAt?: string;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTaskById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    updateTask: {
        parameters: {
            query?: {
                number?: number;
                description?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLabById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LaboratoryWork"];
                };
            };
        };
    };
    updateLab: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaboratoryWork"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LaboratoryWork"];
                };
            };
        };
    };
    deleteLab: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSubmission"];
                };
            };
        };
    };
    checkSolution: {
        parameters: {
            query?: {
                reportType?: "TWO_GRAPH" | "MERGED_GRAPH";
                method?: "BRANCH" | "BRUTE_FORCE" | "DP" | "UNIQUE_LABEL";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GitComparisonResultDto"];
                };
            };
        };
    };
    compareFiles: {
        parameters: {
            query?: {
                reportType?: "TWO_GRAPH" | "MERGED_GRAPH";
                method?: "BRANCH" | "BRUTE_FORCE" | "DP" | "UNIQUE_LABEL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    reference: string;
                    /** Format: binary */
                    student: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GitComparisonResultDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    getAllTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    createTask: {
        parameters: {
            query: {
                number: number;
                description: string;
                labId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    getAllStudents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    createStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    assignTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSubmission"];
                };
            };
        };
    };
    gradeSubmission: {
        parameters: {
            query: {
                grade: number;
                feedback?: string;
            };
            header?: never;
            path: {
                submissionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSubmission"];
                };
            };
        };
    };
    checkSubmission: {
        parameters: {
            query?: {
                reportType?: "TWO_GRAPH" | "MERGED_GRAPH";
                method?: "BRANCH" | "BRUTE_FORCE" | "DP" | "UNIQUE_LABEL";
            };
            header?: never;
            path: {
                submissionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GitComparisonResultDto"];
                };
            };
        };
    };
    getAllLabs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LaboratoryWork"][];
                };
            };
        };
    };
    createLab: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaboratoryWork"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LaboratoryWork"];
                };
            };
        };
    };
    getLabs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LaboratoryWorkDto"][];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    getStudentSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSubmission"][];
                };
            };
        };
    };
    getAllSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StudentSubmission"][];
                };
            };
        };
    };
    getTasksByLabId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"][];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
